version: '3.7'
services:
  httpd:
    image: yoannisj/craftcms-tests-nginx:${NGINX_VERSION:-stable}
    build:
      context: .
      dockerfile: ./docker/httpd/nginx/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-latest}
    environment:
      NGINX_VERSION: ${NGINX_VERSION:-stable}
      WEB_PORT: ${WEB_PORT:-8080}
      WEB_HOSTNAME: ${WEB_HOSTNAME:-localhost}
    volumes:
      - ./docker/httpd/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - cpresources:/app/web/cpresources
    networks:
      - craftcms_tests_net
    ports:
      - target: '${WEB_PORT:-8080}'
        published: '${PUBLIC_PORT_PREFIX}${WEB_PORT:-8080}'
    init: true
    depends_on:
      - craft-web
  craft-web: &craft-service
    image: yoannisj/craftcms-tests:${PHP_VERSION:-7.4}-php-fpm
    build:
      context: .
      dockerfile: ./docker/craftcms/Dockerfile
      args: &craft-service-build-args
        PHP_VERSION: ${PHP_VERSION:-7.4}
        CRAFT_APP_TYPE: php-fpm
        CRAFT_VERSION: ${CRAFT_VERSION:-3.7}
        PACKAGE_NAME: $PACKAGE_NAME
    env_file:
      - .env
    environment: &craft-service-environment
      NGINX_VERSION: ${NGINX_VERSION:-7.4}
      PHP_VERSION: ${PHP_VERSION:-7.4}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-256M}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-120}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-20M}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS:-1000}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-8M}
      PHP_OPCACHE_ENABLE: ${PHP_OPCACHE_ENABLE:-1}
      PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ:-0}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
      PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES:-10000}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION:-256}
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: ${PHP_OPCACHE_MAX_WASTED_PERCENTAGE:-10}
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: ${PHP_OPCACHE_INTERNED_STRINGS_BUFFER:-16}
      PHP_OPCACHE_FAST_SHUTDOWN: ${PHP_OPCACHE_FAST_SHUTDOWN:-1}
      DB_HOST: database
      DB_USER: ${DB_USER:-craftcms}
      DB_PASSWORD: ${DB_PASSWORD:-SecretPassword}
      DB_NAME: ${DB_NAME:-craftcms}
      DB_SCHEMA: ${DB_SCHEMA:-public}
      DB_TABLE_PREFIX: ${DB_TABLE_PREFIX:-craft_}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_VERSION: ${REDIS_VERSION:-5}
      CRAFT_VERSION: ${CRAFT_VERSION:-3.7}
      CRAFT_EDITION: ${CRAFT_EDITION:-solo}
      WEB_URL: ${WEB_URL}
      TUNNEL_URL: ${TUNNEL_URL:-''}
      PRIMARY_SITE_URL: '@web' # used by Craft >= 3.5
      DEFAULT_SITE_URL: '@web' # used by Craft < 3.5
      SECURITY_KEY: $SECURITY_KEY
      PACKAGE_NAME: $PACKAGE_NAME
    volumes: &craft-service-volumes
      - cpresources:/app/web/cpresources
      - ./src:/app/packages/$PACKAGE_NAME/src
      - ./composer.json:/app/packages/$PACKAGE_NAME/composer.json
      - ./docker/craftcms/composer.json:/app/composer.json
      - ./vendor:/app/vendor
      - ./tests:/app/packages/$PACKAGE_NAME/tests
      - ./codeception.yml:/app/packages/$PACKAGE_NAME/codeception.yml
    networks:
      - craftcms_tests_net
    expose:
      - 9000 # exposed to internal networks only
    init: true
    depends_on:
      - database
      - redis
  craft-cli: &craft-cli-service
    <<: *craft-service
    image: yoannisj/craftcms-tests:${PHP_VERSION:-7.4}-cli
    build:
      context: .
      dockerfile: ./docker/craftcms/Dockerfile
      args:
        <<: *craft-service-build-args
        CRAFT_APP_TYPE: cli
    environment:
      <<: *craft-service-environment
      CRAFT_APP_TYPE: cli
    entrypoint: [ "php", "./craft" ]
    command: [ "help" ]
    init: true
  craft-queue:
    <<: *craft-cli-service
    entrypoint: [ "/bin/sh" ]
    command: [ "./craft_queue_listen.sh" ]
  codecept:
    <<: *craft-cli-service
    volumes_from:
      - craft-web
    volumes:
      - ./tests:/app/tests
      - ./codeception.yml:/app/codeception.yml
    working_dir: /app/packages/$PACKAGE_NAME
    entrypoint: [ "php", "/app/vendor/bin/codecept" ]
  database:
    # environment defined in ./docker/database/<db-driver>/docker-compose.override.yml
    # volumes defined in ./docker/database/<db-driver>/docker-compose.override.yml
    init: true
    networks:
      - craftcms_tests_net
    # ports defined in ./docker/database/<db-driver>/docker-compose.override.yml
  redis:
    image: redis:${REDIS_VERSION:-5}-alpine
    init: true
    networks:
      - craftcms_tests_net
    ports:
      - target: '${REDIS_PORT:-6379}'
        published: '${PUBLIC_PORT_PREFIX}${REDIS_PORT:-6379}'
  ngrok:
    image: wernight/ngrok
    environment:
      TUNNEL_TARGET_HOST: httpd
      TUNNEL_TARGET_PORT: ${WEB_PORT:-8080}
      NGROK_LOOK_DOMAIN: http://httpd
      NGROK_PORT: ${WEB_PORT:-8080}
      NGROK_PROTOCOL: ${TUNNEL_PROTOCOL:-HTTP}
      NGROK_AUTH: ${NGROK_AUTH:-''}
      NGROK_SUBDOMAIN: ${NGROK_SUBDOMAIN:-''}
      NGROK_REGION: ${NGROK_REGION:-''}
      NGROK_BINDTLS: ${TUNNEL_BINDTLS:-true}
      NGROK_DEBUG: ${TUNNEL_DEBUG:-true}
    init: true
    networks:
      - craftcms_tests_net
    ports:
      - ${PUBLIC_PORT_PREFIX}${TUNNEL_PORT:-4040}:${TUNNEL_PORT:-4040}
    depends_on:
      - httpd
volumes: # docker internal networks
  cpresources:
    driver: local
networks: # docker internal networks
  craftcms_tests_net:
    driver: bridge # default docker network driver
